version: '3.7'
services:
    mysql:
        container_name: 'api_db'
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./develop/config/mysql:/etc/mysql/conf.d
            - ./develop/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app_db

    phpmyadmin:
        depends_on:
          - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - '8081:80'
        environment:
          PMA_HOST: mysql
          MYSQL_ROOT_PASSWORD: root

    api:
        container_name: 'api_app_1'
        build: ./server
        restart: always
        volumes:
            - ./server:/app
            - ./develop:/app/develop
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        environment:
            - ENVIRONMENT='dev'
            - WAIT_HOSTS=mysql:3306
            - MYSQL_HOST=mysql
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
