version: '3.7'

networks:
    backend:
        driver: bridge

volumes:
    mysql-vol:
        driver: local
    api-vol:
        driver: local

services:
    mysql:
        container_name: 'api_db'
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./develop/config/mysql:/etc/mysql/conf.d
            - mysql-vol:/var/lib/mysql
        networks:
            - backend
        environment:
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app_db

    api:
        container_name: 'api_app_1'
        build: ./server
        restart: always
        volumes:
            - ./server:/app
            - api-vol:/app/develop
        ports:
            - "8080:8080"
        networks:
            - backend
        environment:
            - ENVIRONMENT='dev'
            - WAIT_HOSTS=mysql:3306
            - MYSQL_HOST=mysql
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
