# Generated by Django 2.2.13 on 2020-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roy',
            },
        ),
    ]
