# Generated by Django 2.2.13 on 2020-07-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaser',
            old_name='name',
            new_name='aaaname',
        ),
    ]
